### ISSUE TITLE
Travis CI build is broken

### ISSUE THREAD

**Issue by peter279k** [lstrojny/hmmmath#2]
As title, it causes CI broken because the specific ```ruleset.xml``` is not existed.
Please see more details about this [CI job log](https://travis-ci.org/lstrojny/hmmmath/jobs/395975410).

It should be fixed and I notice that it depends on another package named ```internations/kodierungsregelwerksammlung```.
I think it should fix this problem.
Why not setting the released version instead of using the ```dev-master``` version?

**Comment by lstrojny** [comment]
Fixed in d2305def0864497dea0250d483fd284d4eb4cbdc, thank you!
